version: '3.7'

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch-node1
    environment:
      - cluster.name=docker-cluster
      - node.name=node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"  # Aloca memória para o Java
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"  # Porta de comunicação HTTP
      - "9600:9600"  # Porta para o OpenSearch Monitoring (se necessário)
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-net
    restart: always

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.10.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200  # URL de conexão com o OpenSearch
    ports:
      - "5601:5601"  # Porta para acessar o Dashboards
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1
    restart: always

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge
