version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=LrX5HBcUP47Ca1JfUERT
      - SEQ_FIRSTRUN_REQUIREAUTHENTICATIONFORHTTPINGESTION=True
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    networks:
      - seq_network
volumes:
  seq_data:
    driver: local

networks:
  seq_network:
    driver: bridge